### ISSUE TITLE
[HU 07] - Gerar notificações

### ISSUE THREAD

**Issue by DaviAntonio** [fga-eps-mds/2022-2-CAPJu-Doc#132]
# [HU 07] - Gerar notificações

## Descrição

Como Estagiário, Servidor ou Diretor, eu desejo receber notificações sobre processos atrasados para que eu possa garantir que esses processos recebam a atenção necessária. Dessa forma, eu estarei ciente dos processos que precisam de intervenção e poderei agir rapidamente para minimizar qualquer impacto negativo decorrente do atraso.

## Critérios de aceitação

- [x] Um processo é considerado atrasado se permanecer em uma etapa além do prazo registrado para ela
- [x] Sistema deve verificar processos atrasados às 23:59 diariamente, excluindo sábados e domingos
- [x] #141
- [x] Sistema deve gerar notificações por e-mail sobre processos atrasados para os usuários registrados nos fluxos que incluem o processo

**Comment by DaviAntonio** [comment]
Migração da fga-eps-mds/2022-2-CAPJu-Service#13

**Comment by well1981** [comment]
Critérios de aceitação > Sistema calcula atraso do processo usando o dia atual e o dia em que o processo entrou na etapa. > Comentário: deve considerar também o prazo fixado para a tarefa.

**Comment by AntonioAldisio** [comment]
@well1981 o critério de aceitação ficaria assim:
Sistema calcula atraso do processo usando o dia atual, o dia em que o processo entrou na etapa e o prazo fixado para a tarefa.

**Comment by well1981** [comment]
Recebi o e-mail de notificação.
