### ISSUE TITLE
Migrar Banco de Dados e Remodelar Base de Dados

### ISSUE THREAD

**Issue by DaviAntonio** [fga-eps-mds/2022-2-CAPJu-Doc#136]
# Migrar Banco de Dados e Remodelar Base de Dados

## Descrição

Migrar o Banco de Dados do modelo não-relacional para o relacional. Atualizar a modelagem do Banco de Dados e implementá-la no projeto. Unificar modificações no *front-end* e no *back-end*.
  
## Tarefas
- [x] Atualizar a modelagem com processo terminado
- [x] Atualizar a modelagem com pertencer a vários fluxos
- [x] Configurar atributo para número do processo padrão CNJ
- [x] Atualizar o modelo com cadastro de usuários da unidade que receberão os e-mails de atraso de processos em etapa
- [ ] Atualizar o modelo com cadastro de dias sem expediente
- [ ] Atualizar o modelo para atribuir as estatísticas aos processos nos fluxos
- [x] Decidir o ORM
- [x] Preparar classes de modelo para o ORM
- [x] Criar esquema no PostgreSQL
  - [x] Criar *migrations* necessárias para criar as tabelas e as restrições
- [x] Popular banco com um sysadmin
- [x] Preparar imagem docker para o SGBD

### Número do processo 
- [x] Número do processo armazenado em VARCHAR(20)
  - [x] 20 dígitos (caracteres)

### Validações no front-end
- [ ] padrão CNJ (NNNNNNN-DD.AAAA.J.TR.OOOO)
  - [ ] 6 campos OBRIGATÓRIOS (máscara)
- [ ]  O campo (NNNNNNN), com 7 dígitos, identifica o número sequencial do processo por unidade de origem (OOOO)
- [ ] O campo (DD), com 2 dígitos, identifica o dígito verificador
- [ ]  campo (AAAA), com 4 dígitos, identifica o ano do ajuizamento do processo.
- [ ] O campo (J), com 1 dígito, identifica o órgão ou segmento do Poder Judiciário
- [ ] O campo (TR), com 2 (dois) dígitos, identifica o tribunal do respectivo segmento do Poder Judiciário e, na Justiça Militar da União, a Circunscrição Judiciária
- [ ] O campo (OOOO), com 4 (quatro) dígitos, identifica a unidade de origem do processo

### Integração
- [ ] integrar modificações no *front-end* e *back-end*
  - [ ] ajustar *endpoints*
  - [x] remoção dos *Schemas* e refatoração de alguns métodos acoplados ao MongoDB

### Imagem docker
- [ ] imagem docker do Postgres deve ser integrada aos microsserviços do projeto

### Código
- [x] ORM integrado à base de dados
- [x] Classes de modelos implementadas
- [x] População dos dados iniciais
  - [x] Criação de usuário administrador

### Documentação
- [x] Disponibilizar Modelo Entidade-Relacionamento

## Informação Adicional (se aplicável)

[Padrão CNJ atualizado até 2022-11-29](https://atos.cnj.jus.br/files/compilado23285720221017634de539229ab.pdf)

**Comment by DaviAntonio** [comment]
Tarefa gerada a partir da migração e unificação de fga-eps-mds/2022-2-CAPJu-Service#4 e fga-eps-mds/2022-2-CAPJu-Service#5

**Comment by AntonioAldisio** [comment]
Inclusão de swagger no enpoint /api/v1/docs e / com retorno backend UP

**Comment by DaviAntonio** [comment]
Fechado devido a fga-eps-mds/2022-2-CAPJu-Service#19 e fga-eps-mds/2022-2-CAPJu-Interface#69
