### ISSUE TITLE
Serviço de envio de e-mail

### ISSUE THREAD

**Issue by LucasLopesFrazao** [fga-eps-mds/2022-2-CAPJu-Doc#152]
# Serviço de envio de e-mail

## Descrição
Criar um serviço para enviar e-mail contendo uma tabela com os processos em atraso, quem deve receber este e-mail é aquele que foi cadastrado como participante de um fluxo no sistema.

## Critérios de aceitação
- [ ] Conter a identidade visual da justiça federal (acessar manual do cjf identidade visual).
- [ ] Envio de e-mail único contendo todos os processos atrasados.
- [ ] Sistema calcula atraso do processo usando o dia atual, o dia em que o processo foi iniciado e o prazo fixado para a tarefa.

## Protótipo
![image](https://user-images.githubusercontent.com/89523373/213593738-469be8d3-27e2-4ec7-a884-67e2d31226be.png)

**Comment by well1981** [comment]
Informar o número do processo no e-mail > entendo que isso pode ser retirado, tendo em vista a existência do critério "Envio de e-mail único **_contendo todos os processos atrasados_**".

**Comment by well1981** [comment]
Sugiro alterar o assunto do e-mail de "Atrasos nos processos" para "CAPJU - relatório de processos atrasados".
