### ISSUE TITLE
[HU 08] - Impedir etapas com o mesmo nome

### ISSUE THREAD

**Issue by ilus1** [fga-eps-mds/2022-2-CAPJu-Doc#154]
# [HU 08] - Impedir etapas com o mesmo nome

## Descrição

Como Estagiário, Servidor ou Diretor, eu desejo impedir a criação de etapas iguais, para garantir que não existam etapas conflitantes no sistema. 

## Link para acesso ao sistema: 
https://capju.vercel.app/

## Credenciais de acesso:
cpf: 12345678901
senha: 123Teste

## Critérios de aceitação

- [x] Deve ser possível cadastrar uma nova etapa no sistema.
- [x] Uma etapa não pode ser cadastrada se o sistema já tem outra etapa com mesmo nome e a duração. (incluindo nomes iguais com letras maiúsculas)
- [x] Uma etapa não pode ser cadastrada se o sistema já possui outra etapa com nome igual, mesmo que a duração seja diferente. (incluindo nomes iguais com letras maiúsculas)

**Comment by well1981** [comment]
Após os testes, verifiquei que apareceram os erros "etapa já existe" e "erro ao adicionar etapa". Então a funcionalidade está correta. Sugestão: pode não trazer os dados da última etapa criada quando adicionar uma nova?
