### ISSUE TITLE
[Tarefa - 04] Documentar rótulos

### ISSUE THREAD

**Issue by DaviAntonio** [fga-eps-mds/2022-2-CAPJu-Doc#34]
Incluir documentação sobre os rótulos, também conhecidos como etiquetas, usados nos repositórios.

## Descrição.

Incluir documentação sobre os rótulos, também conhecidos como etiquetas, usados nos repositórios.
  
## Critérios de aceitação

Documentar:

- [x] rótulos personalizados #33 
- [x] rótulos padrões #33
- [x] *bug* usado para defeitos
- [x] *enhancement* usada para melhorias

**Comment by AntonioAldisio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Doc/34?planning-poker) with Zenhub @DaviAntonio @ilus1 @vitorAlves7 @luderibeiro
