### ISSUE TITLE
[Tarefa - 06] Integração do SonarQube na esteira de CICD

### ISSUE THREAD

**Issue by DaviAntonio** [fga-eps-mds/2022-2-CAPJu-Doc#36]
## Descrição

O SonarQube deve ser integrado na esteira (*pipeline*) de integração e implantação contínuas.

## Critérios de aceitação

Configurações gerais
- [ ] a chamada a API do Sonar deve ser orquestrada em um pipeline em cada repositório de código-fonte (microsserviço)
- [ ] deve haver a automação que execute a suíte de testes automatizados e “informe” o relatório da execução ao sonarclooud. 
- [ ] automatizar a execução da suíte de testes automatizados
- [ ] automatizar o fornecimento do relatório da execução da suíte de testes automatizados ao SonarQube
- [ ] escrever o arquivo `sonar-project.properties`
- [ ] deve-se excluir da análise os diretórios e arquivos que não são de código-fonte, por exemplo, arquivos de testes

Geração a cada lançamento
- [ ] deve haver um diretório `analytics-raw-data` no repositório de documentação
- [ ] armazenar **todos** os arquivos gerados com as métricas fornecidas pelo SonarQube, para cada versão do produto (releases major e minor, assim como PR/MR fechado). 
- [ ] criar uma função no respectivo pipeline para disponibilizar o arquivo coletado com as métricas das versões de produto, no diretório `analytics-raw-data` .
- [ ] a cada versão de produto gerada nos repositórios, disponibilizar, via *assets*, no GitHub, o arquivo JSON extraído do serviço do SonarCloud.io
- [ ] o nome do arquivo JSON a ser gerado deve seguir o seguinte formato:
- [ ] `fga-eps-mds-YYYY_SEMESTRE_UNB-NOME_PROJETO-NOME_REPOSITORIO-DATA_HORA_RELEASE-VERSAO_RELEASE` (`fga-eps-mds-2021-2-CartografiaSocial-front-05-07-2022-04-51-38-v3.0.1.json`) onde: 
  - [ ] 1) DATA_HORA_RELEASE deve ter o formato MM-DD-YYYY-HH-MM-SS 
  - [ ] 2) VERSAO_RELEASE = vX.Y.Z sendo: X é a versão principal (ou major); Y é a versão secundária (ou minor); Z é a versão de correção rápida (ou patch); e, X, Y e Z pertencem ao conjunto dos números inteiros positivos

## Informações adicionais

- O SonarCloud faz a integração automática com seus repositórios na organização da disciplina, sem necessitar de um *trigger* externo
- Para adicionar os repositórios  na organização do SonarCloud das disciplinas você precisa ter a permissão de *owner* no GitHub. Para isso:
1. crie sua conta na organização do SonarCloud com o mesmo usuário do GitHub:
- https://sonarcloud.io/organizations/fga-eps-mds-1/projects?sort=name
2. adicione cada repositório de código-fonte (microsserviços) na organização das disciplinas
- [Documentação da SonarCloud sobre cobertura de testes](https://docs.sonarcloud.io/enriching/test-coverage/test-coverage-parameters/)
- [Documentação da SonarCloud sobre execução de testes automatizados](https://docs.sonarcloud.io/enriching/test-coverage/test-execution-parameters/)

**Comment by AntonioAldisio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Doc/36?planning-poker) with Zenhub @DaviAntonio @ilus1 @luderibeiro @vitorAlves7
