### ISSUE TITLE
[Tarefa - 09] - Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Doc#37]
## Descrição.

Disponibilização de um ambiente que tenha o código fonte referente a branch develop

## Critérios de aceitação

- [ ] URL de acesso publico

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Doc/37?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
