### ISSUE TITLE
[Tarefa - 10] - Ambiente de homolagação

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Doc#38]
## Descrição.

Disponibilização de um ambiente que tenha o código fonte referente a branch main

## Critérios de aceitação

- [ ] URL de acesso publico

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Doc/38?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
