### ISSUE TITLE
Criação de documentos de Custos, Riscos e Qualidade.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2022-2-CAPJu-Doc#40]
# Documentos, planilhas e gráficos de Custo, Risco e Qualidade.

## Descrição.

Criação dodocumentos e respectivas planilhas de Custo, Risco e Qualidade.

## Critérios de aceitação

- [x] Doc de Riscos
- [x] Planilhas de Riscos
- [x] Doc de Custos
- [x] Planilha de Custos
- [x] Doc de Qualidade

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Doc/40?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
