### ISSUE TITLE
[HU 03] - Autenticação dos usuários

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Doc#94]
## Descrição

Como Administrador do sistema,
eu quero que a autenticação do sistema ocorra com CPF no campo de login,
para que usuário possa usar o CPF como chave única de acesso.

## Critérios de aceitação

- [x] Usuário ser registrado com CPF.
- [x] CPF utilizado deve ser um CPF válido.
- [x] Usuário se autentica no sistema utilizando CPF.
- [x] Nome de cadastro deve conter no mínimo 1 sobrenome.

#### Usuário quer solicitar registro

Dado que um usuário não está registrado no sistema,
- [x] quando ele informar CPF válido, senha não vazia de até 256 caracteres, e-mail de até 256 caracteres, nome com no mínimo duas palavras e no máximo 300 caracteres, e a unidade em que deseja se cadastrar,
- [x] e solicitar cadastro,
- [x] gerar-se-á uma requisição de cadastro.

#### Usuário quer solicitar registro com dados inválidos

Dado que um usuário não está registrado no sistema,
- [x] quando ele informar CPF inválido, senha vazia ou com mais de 256 caracteres, e-mail vazio ou com mais de 256 caracteres, nome vazio, com apenas uma palavra, ou com mais de 300 caracteres, ou não informar a unidade em que deseja se cadastrar,
- [x] não deve ser possível solicitar o cadastro, e o usuário deve ser informado do erro que ocorreu.

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Doc/94?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7

**Comment by DaviAntonio** [comment]
Atualizou-se a História com Cenários.
