### ISSUE TITLE
[HU 04] - Estatísticas dos processos

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Doc#95]
## Descrição

Como usuário,
Eu quero poder visualizar as estatísticas dos processos cadastrados no sistema,
Para que possa ter métricas quantificadas em cada processo que possa ajudar a identificar padrões e tomar decisões.

## Critérios de aceitação

- [ ] O usuário deve ser capaz de filtrar as estatísticas exibidas por tipo de processo ou período de tempo
- [ ] As estatísticas exibidas devem incluir pelo menos as seguintes informações: quantidade de processos em cada etapa comparando com o total de processos do fluxo, tempo médio gasto em cada etapa (considerar o tempo gasto para avançar a etapa) comparando com o tempo definido para a etapa, quantidade de processos concluídos em um determinado período (mês/ano)
- [ ] A página de estatísticas de processos deve exibir informações sobre todos os processos cadastrados no sistema
- [ ] O usuário deve ser capaz de filtrar as estatísticas exibidas por tipo de processo ou período de tempo
- [ ] A página de estatísticas de processos deve exibir informações sobre todos os processos cadastrados no sistema > todos do mesmo fluxo em que se pretende a pesquisa

**Comment by well1981** [comment]
O usuário deve ser capaz de filtrar as estatísticas exibidas por tipo de processo ou período de tempo > não necessariamente filtrar; pode ser um relatório previamente definido

**Comment by well1981** [comment]
As estatísticas exibidas devem incluir pelo menos as seguintes informações:... > incluir os relatórios indicados no discord anteriormente. São eles:
- quantidade de processos em cada etapa comparando com o total de processos do fluxo
- tempo médio gasto em cada etapa (considerar o tempo gasto para avançar a etapa) comparando com o tempo definido para a etapa
- quantidade de processos concluídos em um determinado período (mês/ano)

**Comment by well1981** [comment]
A página de estatísticas de processos deve exibir informações sobre todos os processos cadastrados no sistema > todos do mesmo fluxo em que se pretende a pesquisa
