### ISSUE TITLE
[HU 06] - Cadastro de Processos

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Doc#97]
## Descrição

Eu como usuário com permissão para cadastrar processo, quero poder cadastrar processos,
para poder fazer o controle e acompanhamento de etapas até a finalização do processo.

## Critérios de aceitação

- [ ] Deve ser possível adicionar um registro, apelido e fluxo ao qual o processo está atrelado.
- [ ] O sistema deve exibir o processo cadastrado na lista de processos.
- [ ] O sistema deve mostrar os processos prioritários
- [ ] O sistema deve mostrar os tipos de prioridades na hora do cadastro
- [ ] Os processos prioritários deverão ter um símbolo de identificação que indica prioridade
- [ ] Deve ser possível adicionar um atributo de prioridade

[Protótipo da HU](https://www.figma.com/proto/v5uz44vsEZvjAeLpVfCbRA/Untitled?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2&show-proto-sidebar=1)
[Link de Teste do Ambiente](https://capju-ix8xswp56-capjudesenv.vercel.app/)

Credenciais para testar o ambiente:

Diretor:
49865986000
123Teste

Juiz:
94922072063
123Teste

Estagiario:
25334947043
123Teste

Servidor:
48973965069
123Teste

**Comment by well1981** [comment]
Deve ser possível adicionar um número, nome e apelido ao processo. > seria interessante eu ver o sistema para conferir se são somente esses dados necessários (navegar na ferramenta); é possível dar esse acesso? em caso positivo, fornecer o caminho.

**Comment by well1981** [comment]
O sistema deverá exibir o processo cadastrado na lista de processos. > na lista de processos de um determinado fluxo

**Comment by well1981** [comment]
Botão de adicionar processo fora do lugar e aparece o botão "log in to comment".

**Comment by well1981** [comment]
Os campos da etapa "criar processo" estão corretos, mas não foi possível "confirmar".

**Comment by well1981** [comment]
O sistema deve exibir o processo cadastrado na lista de processos > prejudicado por conta do comentário anterior.

**Comment by well1981** [comment]
O sistema deve mostrar os processos prioritários > não consegui visualizar quais são os processos prioritários na lista existente; segue anexa a lista de prioridades que devem constar na criação do processo.

![lista de prioridades](https://user-images.githubusercontent.com/121133676/214156629-fd0f3d33-f2ba-4841-aba9-a7089dccd756.png)

**Comment by well1981** [comment]
O sistema deve mostrar os tipos de prioridades na hora do cadastro > isso não está ocorrendo.

**Comment by well1981** [comment]
Os processos prioritários deverão ter um símbolo de identificação que indica prioridade > isso não está ocorrendo.

**Comment by well1981** [comment]
Deve ser possível adicionar um atributo de prioridade > isso pode ser retirado, pois é a mesma coisa que "O sistema deve mostrar os tipos de prioridades na hora do cadastro"

**Comment by well1981** [comment]
> Deve ser possível adicionar um registro, apelido e fluxo ao qual o processo está atrelado > Os campos da etapa "criar processo" estão corretos e o campo para registro das prioridades apareceu no protótipo; acrescentar as prioridades indicadas abaixo.
> 
> ![lista de prioridades](https://user-images.githubusercontent.com/121133676/214178562-2d034313-1907-44f6-a3aa-7b31853ef343.png)

Só faltava validar a inclusão das prioridades e verifiquei que está tudo certo.
